name: latex

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: dxjoke/tectonic-docker
    steps:

    - uses: actions/checkout@v3

    - name: latex
      run: /bin/sh -c "tectonic Daniel-Miller-resume.tex"

    - uses: actions/upload-artifact@v3
      with:
        name: pdf
        path: |
          *.pdf

    # https://github.com/marketplace/actions/upload-files-to-a-github-release
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Daniel-Miller-resume.pdf
        asset_name: Daniel-Miller-resume.pdf
        tag: ${{ github.sha }}
        overwrite: true
      if: github.ref == 'refs/heads/master'
